"""Recent changes to the user's is_verified column

Revision ID: 24c152c5d39a
Revises: 66f302c9fdb4
Create Date: 2026-10-10 16:43:56.456064

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '24c152c5d39a'
down_revision: Union[str, Sequence[str], None] = '66f302c9fdb4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
